import { Geist, Geist_Mono } from "next/font/google";

import type { Metadata } from "next";
import "@/app/globals.css";
import { ThemeProvider } from "@/features/theme/components/theme-provider";
import { cn } from "@/lib/utils";
import { ReactFlowProvider } from "@xyflow/react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={cn(
          "w-screen h-screen antialiased",
          geistSans.variable,
        )}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
          >
          <ReactFlowProvider>
            {children}
          </ReactFlowProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
